name: PlatformIO Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
  egs52_fw:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - name: Build EGS52 FW
        run: |
          pio run -e egs52
      - uses: actions/upload-artifact@v3
        with:
          name: EGS52_FW
          path: |
            .pio/build/egs52/firmware.elf
            .pio/build/egs52/firmware.bin
  egs53_fw:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - name: Build EGS53 FW
        run: |
          pio run -e egs53
      - uses: actions/upload-artifact@v3
        with:
          name: EGS53_FW
          path: |
            .pio/build/egs53/firmware.elf
            .pio/build/egs53/firmware.bin
        
